[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
envconfig = "0.11.0"
tokio = { version = "1.48.0", features = ["full", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
thiserror = "2.0.17"
axum = { version = "0.8.6", features = ["macros"] }
serde = { version = "1.0.228", features = ["derive"] }
tower = "0.5.0"
tower-http = { version = "0.6.6", features = ["cors", "fs", "normalize-path"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "chrono", "macros", "uuid"] }
chrono = { version = "0.4.42", features = ["serde"] }
validator = { version = "0.20.0", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4", "fast-rng"] }
argon2 = "0.5.3"
async-trait = "0.1.89"
jsonwebtoken = { version = "10.1.0", features = ["aws_lc_rs"] }
bb8-redis = "0.24.0"
axum-extra = { version = "0.12.1", features = ["cookie"]}
time = "0.3.44"
slug = "0.1.6"
sqlx-adapter = { version = "1.8.0", default-features = false, features = ["postgres", "runtime-tokio-rustls"]}
casbin = { version = "2.16.0", default-features = false, features = ["runtime-tokio", "logging", "incremental"] }
reqwest = { version = "0.12.24", features = ["json"] }
base64 = "0.22.1"
