[package]
name = "backend"
version = "0.1.0"
authors = ["Michael Mooney <mikeymooney1991@gmail.com>"]
edition = "2021"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = {version = "1.45.1", features = ["full"]}
sqlx = { version = "0.8.6", features = [ "runtime-tokio-rustls", "migrate", "uuid", "postgres", "macros"], default-features = false }
rand = "0.9.1"
argon2 = "0.5.3"
thiserror = "2.0.12"
chrono = { version = "0.4.41", features = ["serde", "clock", "unstable-locales" ] }
time = { version = "0.3", features = ["serde", "formatting", "macros"] }
uuid = { version= "1.17.0", features = ["v4", "serde"] }
dotenvy = "0.15.7"
tower-sessions = "0.14.0"
http = "1.3.1"
tower = "0.5.0"
tower-http = { version = "0.5.2", features = ["full"] }
tower-sessions-sqlx-store = { version = "0.15.0", features = [ "postgres" ] }
validator = { version = "0.17", features = [ "derive" ] }
reqwest = { version = "0.12.20", features = [ "json" ] }
byte-unit = "4"
lazy_static = "1"
